### ISSUE TITLE
[Feature request]: option to download videos from prismic

### ISSUE THREAD

**Issue by MarcMcIntosh** [prismicio/gatsby#333]
One of our users noticed that videos in prismic caused their cdm usage to increase by a substantial amount, as video files had to be retrieved from prismic every time the page was visited. 

After looking through of solutions to help the user get their usage down I found that there is a way to fetch videos from a remote host and serve the files along with the site.
https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/#createremotefilenode

Do you think should we add this functionality?

**Comment by angeloashmore** [comment]
Yes, definitely. Luckily, this has already been implemented in V4 (in the `alpha` branch) as part of link/media fields.

https://github.com/angeloashmore/gatsby-source-prismic/tree/556cf778901b761459ad0896c14e02b622306407/packages/gatsby-source-prismic#query-media-fields

Excerpt taken from the draft README:

---

### Query Media fields

Media fields can be populated with files such as PDFs, ZIPs, or images. The URL
to a field's file can be served from Prismic's CDN or can be downloaded locally
to be served with your app.

Querying for the `localFile` field will tell Gatsby to download the file
locally. To add `publicURL` as an available field, which copies the file into
your app's `/static` directory, add
[`gatsby-source-filesystem`][gatsby-source-filesystem] to your project.

**Note**: `gatsby-source-filesystem` requires pointing the plugin to a directory
within your app. If you aren't using `gatsby-source-filesystem` for any other
purpose in your app, you can set its `path` parameter to any directory in your
project. Adding `gatsby-source-filesystem` is the only way to register the
`publicURL` field.

```graphql
{
  allPrismicPage {
    edges {
      nodes {
        data {
          media_field {
            url
            localFile {
              publicURL
            }
          }
        }
      }
    }
  }
}
```

**Comment by MarcMcIntosh** [comment]
Nice, I'll pass this information along :)

**Comment by angeloashmore** [comment]
V4 has been published!

[gatsby-source-prismic](https://github.com/prismicio/gatsby/tree/main/packages/gatsby-source-prismic) downloads media files locally when the `localFile` field is queried (described in the previous comment).
