### ISSUE TITLE
Gatsby + Prismic V4 Public Beta

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/gatsby#377]
Hey everyone!

# 🎉 The Gatsby + Prismic integration is being updated! 🎉

I'm excited to have everyone try it out in its current **beta** version and get your feedback.

A comprehensive list of new features and fixes is available here: ["What has changed?" on GitHub](https://github.com/angeloashmore/gatsby-source-prismic/blob/beta/packages/gatsby-source-prismic/docs/migrating-from-v3-to-v4.md#what-has-changed)

If you are starting a new project or have the ability to upgrade an existing project, please give the updated plugins a try.

> ⚠️ **Note**: This is a **beta** release, which means there may be bugs or unintended behaviors.
>
> We need feedback on real, complex projects, but we also don't want to compromise your website and development flow. Please keep this in mind if your project is already in production.

The official documentation on https://prismic.io will be updated for the new plugins. Until they are officially published, all new documentation will be on GitHub, linked below.

## `gatsby-source-prismic`

**Latest version**: `v4.0.0-beta.17`

This is the same Gatsby plugin you use today, now with new features and a number of refinements. Preview functionality has been moved to its own plugin (`gatsby-plugin-prismic-previews`), described below.

**Overview**: [`gatsby-source-prismic` on GitHub](https://github.com/angeloashmore/gatsby-source-prismic/tree/beta/packages/gatsby-source-prismic)
**Migration Guide**: [Migrate `gatsby-source-prismic` from V3 to V4](https://github.com/angeloashmore/gatsby-source-prismic/blob/beta/packages/gatsby-source-prismic/docs/migrating-from-v3-to-v4.md)

## `gatsby-plugin-prismic-previews`

**Latest version**: `v4.0.0-beta.18`

This is a new plugin that handles all preview-related functionality. This was previously part of `gatsby-source-prismic` which has been extracted and rearchitected for better Prismic Previews support.

**Overview**: [`gatsby-plugin-prismic-previews` on GitHub](https://github.com/angeloashmore/gatsby-source-prismic/tree/beta/packages/gatsby-plugin-prismic-previews#gatsby-plugin-prismic-previews)
**Migration Guide**: [Migrating from `gatsby-source-prismic`](https://github.com/angeloashmore/gatsby-source-prismic/blob/beta/packages/gatsby-plugin-prismic-previews/docs/migrating-from-gatsby-source-prismic.md)

# Providing feedback and reporting issues

If you have feedback or need to report a bug, please open an issue on GitHub so we can track features and fixes.

[See all GitHub Issues](https://github.com/angeloashmore/gatsby-source-prismic/issues)
[Open a GitHub Issue](https://github.com/angeloashmore/gatsby-source-prismic/issues/new)

Thank you! As always, we're open to any feedback and input, so please share!

**Comment by cometkim** [comment]
First of all, thank for your awesome work @angeloashmore

I'm trying to migrate projects using v3. Most of features are working fine, and the localFile resolver with remove fallback & graphql-plugin-image support is really great!

The only problem is the preview integration. Following the guide, I specified `repositoryName` (which is a public repo named `karrot`) in gatsby-config and HoCs, but I keep getting errors

![image](https://user-images.githubusercontent.com/9696352/119947870-30a42300-bfd3-11eb-90be-9f62fc62ccdc.png)

----

I'm maintaining some schemaCustomization to negate nullablilty appearing unnecessarily in the generated schema.

It might help to track name rule changes.

```
    type PrismicLinkType {
      isBroken: Boolean!
      url: String!
      target: String!
      raw: JSON!
    }

    type PrismicImageDimensionsType {
      width: Int!
      height: Int!
    }

    type PrismicStructuredTextType {
      html: String!
      text: String!
      raw: JSON!
    }

    type PrismicGeoPointType {
      latitude: Float!
      longitude: Float!
    }
```

```diff
diff --git a/team.daangn.com/gatsby/gatsby-node.ts b/team.daangn.com/gatsby/gatsby-node.ts
index ae2df38..5d4ec6d 100644
--- a/team.daangn.com/gatsby/gatsby-node.ts
+++ b/team.daangn.com/gatsby/gatsby-node.ts
@@ -43,7 +43,7 @@ export const createSchemaCustomization: GatsbyNode['createSchemaCustomization']
     }
 
     type PrismicFaqDataType {
-      entries: [PrismicFaqEntriesGroupType!]!
+      entries: [PrismicFaqDataEntries!]!
     }
   `);
 
@@ -54,9 +54,9 @@ export const createSchemaCustomization: GatsbyNode['createSchemaCustomization']
     }
 
     type PrismicSiteNavigationDataType {
-      header_entries: [PrismicSiteNavigationHeaderEntriesGroupType!]!
-      footer_entries: [PrismicSiteNavigationFooterEntriesGroupType!]!
-      sns_profiles: [PrismicSiteNavigationSnsProfilesGroupType!]!
+      header_entries: [PrismicSiteNavigationDataHeaderEntries!]!
+      footer_entries: [PrismicSiteNavigationDataFooterEntries!]!
+      sns_profiles: [PrismicSiteNavigationDataSnsProfiles!]!
     }
   `);
 
@@ -67,29 +67,29 @@ export const createSchemaCustomization: GatsbyNode['createSchemaCustomization']
     }
 
     type PrismicTeamContentsDataType {
-      main_body: [PrismicTeamContentsMainBodySlicesType!]!
-      culture_body: [PrismicTeamContentsCultureBodySlicesType!]!
-      life_body: [PrismicTeamContentsLifeBodySlicesType!]!
+      main_body: [PrismicTeamContentsDataMainBodySlicesType!]!
+      culture_body: [PrismicTeamContentsDataCultureBodySlicesType!]!
+      life_body: [PrismicTeamContentsDataLifeBodySlicesType!]!
     }
 
     type PrismicTeamContentsMainBodyKeyVisualWithText {
-      primary: PrismicTeamContentsMainBodyKeyVisualWithTextPrimaryType!
+      primary: PrismicTeamContentsDataMainBodyKeyVisualWithTextPrimary!
     }
 
     type PrismicTeamContentsMainBodySummaryAndDetail {
-      primary: PrismicTeamContentsMainBodySummaryAndDetailPrimaryType!
+      primary: PrismicTeamContentsDataMainBodySummaryAndDetailPrimary!
     }
 
     type PrismicTeamContentsMainBodyParagraph {
-      primary: PrismicTeamContentsMainBodyParagraphPrimaryType!
+      primary: PrismicTeamContentsDataMainBodyParagraphPrimary!
     }
 
     type PrismicTeamContentsMainBodySingleIllustration {
-      primary: PrismicTeamContentsMainBodySingleIllustrationPrimaryType!
+      primary: PrismicTeamContentsDataMainBodySingleIllustrationPrimary!
     }
 
     type PrismicTeamContentsMainBodyMemberQuoteCarousel {
-      items: [PrismicTeamContentsMainBodyMemberQuoteCarouselItemType!]!
+      items: [PrismicTeamContentsDataMainBodyMemberQuoteCarouselItem!]!
     }
   `);
```

Or can we declare this by default in the new version of gatsby-source-prismic? I think this is always true and it greatly improves DX if we provide it out-of-box.

----

I'm using [gatsby-plugin-typegen](https://github.com/cometkim/gatsby-plugin-typegen) (which is I'm maintaining) for type-safety and schema traceability and the plugin reporting errors with v4 because there are still fragment exports that are not valid anymore.

the error:
```
AggregateError: GraphQLDocumentError: Unknown type "PrismicImageFixedType". Did you mean "PrismicEmbedType", "PrismicImageDimensionsType", "PrismicSliceType", "PrismicFaqDataType
  ", or "PrismicGeoPointType"?
      GraphQLDocumentError: Unknown type "PrismicImageFixedType". Did you mean "PrismicEmbedType", "PrismicImageDimensionsType", "PrismicSliceType", "PrismicFaqDataType", or "Prism
  icGeoPointType"?
```

exported documents:
```
fragment GatsbyPrismicImageFixed on PrismicImageFixedType {
  base64
  width
  height
  src
  srcSet
}

fragment GatsbyPrismicImageFixed_noBase64 on PrismicImageFixedType {
  width
  height
  src
  srcSet
}

fragment GatsbyPrismicImageFixed_withWebp on PrismicImageFixedType {
  base64
  width
  height
  src
  srcSet
  srcWebp
  srcSetWebp
}

fragment GatsbyPrismicImageFixed_withWebp_noBase64 on PrismicImageFixedType {
  width
  height
  src
  srcSet
  srcWebp
  srcSetWebp
}

fragment GatsbyPrismicImageFluid on PrismicImageFluidType {
  base64
  aspectRatio
  src
  srcSet
  sizes
}

fragment GatsbyPrismicImageFluid_noBase64 on PrismicImageFluidType {
  aspectRatio
  src
  srcSet
  sizes
}

fragment GatsbyPrismicImageFluid_withWebp on PrismicImageFluidType {
  base64
  aspectRatio
  src
  srcSet
  srcWebp
  srcSetWebp
  sizes
}

fragment GatsbyPrismicImageFluid_withWebp_noBase64 on PrismicImageFluidType {
  aspectRatio
  src
  srcSet
  srcWebp
  srcSetWebp
  sizes
}
fragment GatsbyImgixFluid on ImgixFluid {
  aspectRatio
  src
  srcWebp
  srcSet
  srcSetWebp
  sizes
  base64
}

fragment GatsbyImgixFluid_noBase64 on ImgixFluid {
  aspectRatio
  src
  srcWebp
  srcSet
  srcSetWebp
  sizes
}

fragment GatsbyImgixFixed on ImgixFixed {
  base64
  width
  height
  src
  srcSet
  srcWebp
  srcSetWebp
}

fragment GatsbyImgixFixed_noBase64 on ImgixFixed {
  width
  height
  src
  srcSet
  srcWebp
  srcSetWebp
}
```

**Comment by cometkim** [comment]
Instead of having to enter an empty schema for all custom types, it would be better to put in the default values.

In my organization, I'm using a single repository and sharing content schema with many projects,  in the process of people working together, there are a lot of schema additions/deletions, and if content is updated in the meantime, the build breaks unintentionally.

**Comment by angeloashmore** [comment]
Hey @cometkim, thanks for the detailed diagnosis.

I'll answer each of your points below:

---

**1. Preview integration error ("repository could not be found")**

Could you perform this step in your app?

https://github.com/angeloashmore/gatsby-source-prismic/blob/beta/packages/gatsby-plugin-prismic-previews/docs/migrating-from-gatsby-source-prismic.md#update-gatsby-browserjs-and-gatsby-ssrjs-files

I apologize, this step was mistakenly left out of the migration guide before. If this doesn't fix that error, could you open a separate issue?

---

2. GraphQL field nullability

Good points! There are fields that could be deemed non-nullable, like the ones you pointed out.

I'll have to look closer at what fields can actually be non-nullable. For example, a GeoPoint field *may* have null values if it was never set in the editor.

I've opened a issue here to track it: https://github.com/angeloashmore/gatsby-source-prismic/issues/381

If you have time to open a PR, feel free to open one and I can review it. Thank you!

---

3. Invalid image fragments

Thank you for pointing this out. I'll take a look and fix this.

Related issue: https://github.com/angeloashmore/gatsby-source-prismic/issues/382

Also, great work on gatsby-plugin-typegen!

---

4. Use a default value for JSON schemas

This is a common source of problems for many users. Forgetting to provide a schema means the data provided in the GraphQL API will be the incorrect shape. Without an error when a schema is not provided, users don't realize things were setup incorrectly until further in development with no idea why things are broken.

It's possible the error could be downgraded to a warning if a schema is missing, but I feel many users will miss or ignore the warning.

I totally understand the frustration in needing to update the `schemas` option during development. Prismic's new (in beta) Custom Types API could help here as an automated way of populating the `schemas` option. Basically, you would always have the latest up to date version of your schemas without needing to move them locally into your project.

See: https://github.com/angeloashmore/gatsby-source-prismic/tree/beta/packages/gatsby-source-prismic#providing-json-schemas

**Comment by cometkim** [comment]
> It's possible the error could be downgraded to a warning if a schema is missing, but I feel many users will miss or ignore the warning.

or we can provide a plugin option to downgrade it to warninig and keep default to panic on build.

By writing codes as type-safe much as possible, and I can notice problems when previewing instead of breaking the build.

**Comment by angeloashmore** [comment]
### 🎊 V4 is officially published! 🎊

Thank you to everyone who tested out the plugins during the beta period!

New feature requests are tracked in other GitHub issues and will be developed and released in future V4 releases. If you encounter any issues with the latest V4 release, please open an issue and I will take a look!
