### ISSUE TITLE
Broken links in v3 docs. Need versioned docs

### ISSUE THREAD

**Issue by greatwitenorth** [prismicio/gatsby#425]
### Versions

- gatsby-source-prismic: v3

### Reproduction

Visit the following link:
https://github.com/prismicio/gatsby/tree/v3

Try to click the following links:

- Migrating from v2 to v3
- Previews

The links go to 404 pages.

**Additional Details**
We need to have some versioned documentation for this source plugin. We have clients still on v3 and we cannot upgrade them to v4 at the moment. For example, we need to do some debugging `withUnpublishedPreview` and without the v3 docs it's hard to understand how it was originally intended to operate.

It would be really great to see versioned docs similar to how [Laravel](https://laravel.com/docs/8.x/installation) works.

### Steps to reproduce
As noted above

### What is expected?
Working links.

### What is actually happening?
Links go to 404 page.

**Comment by angeloashmore** [comment]
@greatwitenorth Thanks for catching the broken links. I've updated the docs in the `v3` branch to use the correct URLs. Can you let me know if this fixes the issue you had?

Re: versioned docs - Documentation will be on [Prismic's site](https://prismic.io/docs/technologies/gatsby) going forward. Versioning the technical documentation ([this page for example](https://prismic.io/docs/technologies/gatsby-plugin-prismic-previews-technical-reference)) is currently being worked on.

I don't have an estimate when it will be ready, but hopefully it will be before the next minor version change.
